//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace PDS.DataLayer
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PDSEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PDSEntities object using the connection string found in the 'PDSEntities' section of the application configuration file.
        /// </summary>
        public PDSEntities() : base("name=PDSEntities", "PDSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PDSEntities object.
        /// </summary>
        public PDSEntities(string connectionString) : base(connectionString, "PDSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PDSEntities object.
        /// </summary>
        public PDSEntities(EntityConnection connection) : base(connection, "PDSEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PDSFill> PDSFills
        {
            get
            {
                if ((_PDSFills == null))
                {
                    _PDSFills = base.CreateObjectSet<PDSFill>("PDSFills");
                }
                return _PDSFills;
            }
        }
        private ObjectSet<PDSFill> _PDSFills;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PDSPatient> PDSPatients
        {
            get
            {
                if ((_PDSPatients == null))
                {
                    _PDSPatients = base.CreateObjectSet<PDSPatient>("PDSPatients");
                }
                return _PDSPatients;
            }
        }
        private ObjectSet<PDSPatient> _PDSPatients;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PDSPrescriber> PDSPrescribers
        {
            get
            {
                if ((_PDSPrescribers == null))
                {
                    _PDSPrescribers = base.CreateObjectSet<PDSPrescriber>("PDSPrescribers");
                }
                return _PDSPrescribers;
            }
        }
        private ObjectSet<PDSPrescriber> _PDSPrescribers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PDSProduct> PDSProducts
        {
            get
            {
                if ((_PDSProducts == null))
                {
                    _PDSProducts = base.CreateObjectSet<PDSProduct>("PDSProducts");
                }
                return _PDSProducts;
            }
        }
        private ObjectSet<PDSProduct> _PDSProducts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PDSQueueState> PDSQueueStates
        {
            get
            {
                if ((_PDSQueueStates == null))
                {
                    _PDSQueueStates = base.CreateObjectSet<PDSQueueState>("PDSQueueStates");
                }
                return _PDSQueueStates;
            }
        }
        private ObjectSet<PDSQueueState> _PDSQueueStates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PDSRole> PDSRoles
        {
            get
            {
                if ((_PDSRoles == null))
                {
                    _PDSRoles = base.CreateObjectSet<PDSRole>("PDSRoles");
                }
                return _PDSRoles;
            }
        }
        private ObjectSet<PDSRole> _PDSRoles;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PDSRoleTaskMapping> PDSRoleTaskMappings
        {
            get
            {
                if ((_PDSRoleTaskMappings == null))
                {
                    _PDSRoleTaskMappings = base.CreateObjectSet<PDSRoleTaskMapping>("PDSRoleTaskMappings");
                }
                return _PDSRoleTaskMappings;
            }
        }
        private ObjectSet<PDSRoleTaskMapping> _PDSRoleTaskMappings;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PDSRx> PDSRxes
        {
            get
            {
                if ((_PDSRxes == null))
                {
                    _PDSRxes = base.CreateObjectSet<PDSRx>("PDSRxes");
                }
                return _PDSRxes;
            }
        }
        private ObjectSet<PDSRx> _PDSRxes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PDSTask> PDSTasks
        {
            get
            {
                if ((_PDSTasks == null))
                {
                    _PDSTasks = base.CreateObjectSet<PDSTask>("PDSTasks");
                }
                return _PDSTasks;
            }
        }
        private ObjectSet<PDSTask> _PDSTasks;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<PDSUser> PDSUsers
        {
            get
            {
                if ((_PDSUsers == null))
                {
                    _PDSUsers = base.CreateObjectSet<PDSUser>("PDSUsers");
                }
                return _PDSUsers;
            }
        }
        private ObjectSet<PDSUser> _PDSUsers;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PDSFills EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPDSFills(PDSFill pDSFill)
        {
            base.AddObject("PDSFills", pDSFill);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PDSPatients EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPDSPatients(PDSPatient pDSPatient)
        {
            base.AddObject("PDSPatients", pDSPatient);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PDSPrescribers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPDSPrescribers(PDSPrescriber pDSPrescriber)
        {
            base.AddObject("PDSPrescribers", pDSPrescriber);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PDSProducts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPDSProducts(PDSProduct pDSProduct)
        {
            base.AddObject("PDSProducts", pDSProduct);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PDSQueueStates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPDSQueueStates(PDSQueueState pDSQueueState)
        {
            base.AddObject("PDSQueueStates", pDSQueueState);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PDSRoles EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPDSRoles(PDSRole pDSRole)
        {
            base.AddObject("PDSRoles", pDSRole);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PDSRoleTaskMappings EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPDSRoleTaskMappings(PDSRoleTaskMapping pDSRoleTaskMapping)
        {
            base.AddObject("PDSRoleTaskMappings", pDSRoleTaskMapping);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PDSRxes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPDSRxes(PDSRx pDSRx)
        {
            base.AddObject("PDSRxes", pDSRx);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PDSTasks EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPDSTasks(PDSTask pDSTask)
        {
            base.AddObject("PDSTasks", pDSTask);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the PDSUsers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPDSUsers(PDSUser pDSUser)
        {
            base.AddObject("PDSUsers", pDSUser);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDS.DataLayer", Name="PDSFill")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PDSFill : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PDSFill object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="isSold">Initial value of the IsSold property.</param>
        /// <param name="isDueApproved">Initial value of the IsDueApproved property.</param>
        /// <param name="isAdjudicated">Initial value of the IsAdjudicated property.</param>
        /// <param name="isLabelPrinted">Initial value of the IsLabelPrinted property.</param>
        /// <param name="isRPHVerified">Initial value of the IsRPHVerified property.</param>
        /// <param name="rxID">Initial value of the RxID property.</param>
        public static PDSFill CreatePDSFill(global::System.Int32 id, global::System.Boolean isSold, global::System.Boolean isDueApproved, global::System.Boolean isAdjudicated, global::System.Boolean isLabelPrinted, global::System.Boolean isRPHVerified, global::System.Int32 rxID)
        {
            PDSFill pDSFill = new PDSFill();
            pDSFill.ID = id;
            pDSFill.IsSold = isSold;
            pDSFill.IsDueApproved = isDueApproved;
            pDSFill.IsAdjudicated = isAdjudicated;
            pDSFill.IsLabelPrinted = isLabelPrinted;
            pDSFill.IsRPHVerified = isRPHVerified;
            pDSFill.RxID = rxID;
            return pDSFill;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WrittenQty
        {
            get
            {
                return _WrittenQty;
            }
            set
            {
                OnWrittenQtyChanging(value);
                ReportPropertyChanging("WrittenQty");
                _WrittenQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WrittenQty");
                OnWrittenQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _WrittenQty;
        partial void OnWrittenQtyChanging(Nullable<global::System.Int32> value);
        partial void OnWrittenQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DispensedQty
        {
            get
            {
                return _DispensedQty;
            }
            set
            {
                OnDispensedQtyChanging(value);
                ReportPropertyChanging("DispensedQty");
                _DispensedQty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DispensedQty");
                OnDispensedQtyChanged();
            }
        }
        private Nullable<global::System.Int32> _DispensedQty;
        partial void OnDispensedQtyChanging(Nullable<global::System.Int32> value);
        partial void OnDispensedQtyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> WrittenDate
        {
            get
            {
                return _WrittenDate;
            }
            set
            {
                OnWrittenDateChanging(value);
                ReportPropertyChanging("WrittenDate");
                _WrittenDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WrittenDate");
                OnWrittenDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _WrittenDate;
        partial void OnWrittenDateChanging(Nullable<global::System.DateTime> value);
        partial void OnWrittenDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DispensedDate
        {
            get
            {
                return _DispensedDate;
            }
            set
            {
                OnDispensedDateChanging(value);
                ReportPropertyChanging("DispensedDate");
                _DispensedDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DispensedDate");
                OnDispensedDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _DispensedDate;
        partial void OnDispensedDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDispensedDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsSold
        {
            get
            {
                return _IsSold;
            }
            set
            {
                OnIsSoldChanging(value);
                ReportPropertyChanging("IsSold");
                _IsSold = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsSold");
                OnIsSoldChanged();
            }
        }
        private global::System.Boolean _IsSold;
        partial void OnIsSoldChanging(global::System.Boolean value);
        partial void OnIsSoldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsDueApproved
        {
            get
            {
                return _IsDueApproved;
            }
            set
            {
                OnIsDueApprovedChanging(value);
                ReportPropertyChanging("IsDueApproved");
                _IsDueApproved = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsDueApproved");
                OnIsDueApprovedChanged();
            }
        }
        private global::System.Boolean _IsDueApproved;
        partial void OnIsDueApprovedChanging(global::System.Boolean value);
        partial void OnIsDueApprovedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsAdjudicated
        {
            get
            {
                return _IsAdjudicated;
            }
            set
            {
                OnIsAdjudicatedChanging(value);
                ReportPropertyChanging("IsAdjudicated");
                _IsAdjudicated = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsAdjudicated");
                OnIsAdjudicatedChanged();
            }
        }
        private global::System.Boolean _IsAdjudicated;
        partial void OnIsAdjudicatedChanging(global::System.Boolean value);
        partial void OnIsAdjudicatedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsLabelPrinted
        {
            get
            {
                return _IsLabelPrinted;
            }
            set
            {
                OnIsLabelPrintedChanging(value);
                ReportPropertyChanging("IsLabelPrinted");
                _IsLabelPrinted = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsLabelPrinted");
                OnIsLabelPrintedChanged();
            }
        }
        private global::System.Boolean _IsLabelPrinted;
        partial void OnIsLabelPrintedChanging(global::System.Boolean value);
        partial void OnIsLabelPrintedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean IsRPHVerified
        {
            get
            {
                return _IsRPHVerified;
            }
            set
            {
                OnIsRPHVerifiedChanging(value);
                ReportPropertyChanging("IsRPHVerified");
                _IsRPHVerified = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsRPHVerified");
                OnIsRPHVerifiedChanged();
            }
        }
        private global::System.Boolean _IsRPHVerified;
        partial void OnIsRPHVerifiedChanging(global::System.Boolean value);
        partial void OnIsRPHVerifiedChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RxID
        {
            get
            {
                return _RxID;
            }
            set
            {
                OnRxIDChanging(value);
                ReportPropertyChanging("RxID");
                _RxID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RxID");
                OnRxIDChanged();
            }
        }
        private global::System.Int32 _RxID;
        partial void OnRxIDChanging(global::System.Int32 value);
        partial void OnRxIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private Nullable<global::System.Int32> _State;
        partial void OnStateChanging(Nullable<global::System.Int32> value);
        partial void OnStateChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDS.DataLayer", Name="PDSPatient")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PDSPatient : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PDSPatient object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="dOB">Initial value of the DOB property.</param>
        public static PDSPatient CreatePDSPatient(global::System.Int32 id, global::System.String firstName, global::System.String lastName, global::System.DateTime dOB)
        {
            PDSPatient pDSPatient = new PDSPatient();
            pDSPatient.ID = id;
            pDSPatient.FirstName = firstName;
            pDSPatient.LastName = lastName;
            pDSPatient.DOB = dOB;
            return pDSPatient;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MiddleName
        {
            get
            {
                return _MiddleName;
            }
            set
            {
                OnMiddleNameChanging(value);
                ReportPropertyChanging("MiddleName");
                _MiddleName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MiddleName");
                OnMiddleNameChanged();
            }
        }
        private global::System.String _MiddleName;
        partial void OnMiddleNameChanging(global::System.String value);
        partial void OnMiddleNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Phone
        {
            get
            {
                return _Phone;
            }
            set
            {
                OnPhoneChanging(value);
                ReportPropertyChanging("Phone");
                _Phone = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Phone");
                OnPhoneChanged();
            }
        }
        private global::System.String _Phone;
        partial void OnPhoneChanging(global::System.String value);
        partial void OnPhoneChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> IsBillingMethodCash
        {
            get
            {
                return _IsBillingMethodCash;
            }
            set
            {
                OnIsBillingMethodCashChanging(value);
                ReportPropertyChanging("IsBillingMethodCash");
                _IsBillingMethodCash = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IsBillingMethodCash");
                OnIsBillingMethodCashChanged();
            }
        }
        private Nullable<global::System.Boolean> _IsBillingMethodCash;
        partial void OnIsBillingMethodCashChanging(Nullable<global::System.Boolean> value);
        partial void OnIsBillingMethodCashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime DOB
        {
            get
            {
                return _DOB;
            }
            set
            {
                OnDOBChanging(value);
                ReportPropertyChanging("DOB");
                _DOB = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DOB");
                OnDOBChanged();
            }
        }
        private global::System.DateTime _DOB;
        partial void OnDOBChanging(global::System.DateTime value);
        partial void OnDOBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address1
        {
            get
            {
                return _Address1;
            }
            set
            {
                OnAddress1Changing(value);
                ReportPropertyChanging("Address1");
                _Address1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address1");
                OnAddress1Changed();
            }
        }
        private global::System.String _Address1;
        partial void OnAddress1Changing(global::System.String value);
        partial void OnAddress1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address2
        {
            get
            {
                return _Address2;
            }
            set
            {
                OnAddress2Changing(value);
                ReportPropertyChanging("Address2");
                _Address2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address2");
                OnAddress2Changed();
            }
        }
        private global::System.String _Address2;
        partial void OnAddress2Changing(global::System.String value);
        partial void OnAddress2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                OnStateChanging(value);
                ReportPropertyChanging("State");
                _State = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("State");
                OnStateChanged();
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ZIP
        {
            get
            {
                return _ZIP;
            }
            set
            {
                OnZIPChanging(value);
                ReportPropertyChanging("ZIP");
                _ZIP = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ZIP");
                OnZIPChanged();
            }
        }
        private global::System.String _ZIP;
        partial void OnZIPChanging(global::System.String value);
        partial void OnZIPChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDS.DataLayer", Name="PDSPrescriber")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PDSPrescriber : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PDSPrescriber object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        public static PDSPrescriber CreatePDSPrescriber(global::System.Int32 id)
        {
            PDSPrescriber pDSPrescriber = new PDSPrescriber();
            pDSPrescriber.ID = id;
            return pDSPrescriber;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NPI
        {
            get
            {
                return _NPI;
            }
            set
            {
                OnNPIChanging(value);
                ReportPropertyChanging("NPI");
                _NPI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NPI");
                OnNPIChanged();
            }
        }
        private global::System.String _NPI;
        partial void OnNPIChanging(global::System.String value);
        partial void OnNPIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DEA
        {
            get
            {
                return _DEA;
            }
            set
            {
                OnDEAChanging(value);
                ReportPropertyChanging("DEA");
                _DEA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DEA");
                OnDEAChanged();
            }
        }
        private global::System.String _DEA;
        partial void OnDEAChanging(global::System.String value);
        partial void OnDEAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDS.DataLayer", Name="PDSProduct")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PDSProduct : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PDSProduct object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="nDC">Initial value of the NDC property.</param>
        public static PDSProduct CreatePDSProduct(global::System.Int32 id, global::System.String nDC)
        {
            PDSProduct pDSProduct = new PDSProduct();
            pDSProduct.ID = id;
            pDSProduct.NDC = nDC;
            return pDSProduct;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NDC
        {
            get
            {
                return _NDC;
            }
            set
            {
                OnNDCChanging(value);
                ReportPropertyChanging("NDC");
                _NDC = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NDC");
                OnNDCChanged();
            }
        }
        private global::System.String _NDC;
        partial void OnNDCChanging(global::System.String value);
        partial void OnNDCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Image
        {
            get
            {
                return _Image;
            }
            set
            {
                OnImageChanging(value);
                ReportPropertyChanging("Image");
                _Image = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Image");
                OnImageChanged();
            }
        }
        private global::System.String _Image;
        partial void OnImageChanging(global::System.String value);
        partial void OnImageChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDS.DataLayer", Name="PDSQueueState")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PDSQueueState : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PDSQueueState object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="state">Initial value of the State property.</param>
        public static PDSQueueState CreatePDSQueueState(global::System.Int32 id, global::System.String state)
        {
            PDSQueueState pDSQueueState = new PDSQueueState();
            pDSQueueState.ID = id;
            pDSQueueState.State = state;
            return pDSQueueState;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String State
        {
            get
            {
                return _State;
            }
            set
            {
                if (_State != value)
                {
                    OnStateChanging(value);
                    ReportPropertyChanging("State");
                    _State = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("State");
                    OnStateChanged();
                }
            }
        }
        private global::System.String _State;
        partial void OnStateChanging(global::System.String value);
        partial void OnStateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDS.DataLayer", Name="PDSRole")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PDSRole : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PDSRole object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="description">Initial value of the Description property.</param>
        public static PDSRole CreatePDSRole(global::System.String id, global::System.String description)
        {
            PDSRole pDSRole = new PDSRole();
            pDSRole.ID = id;
            pDSRole.Description = description;
            return pDSRole;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                if (_Description != value)
                {
                    OnDescriptionChanging(value);
                    ReportPropertyChanging("Description");
                    _Description = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Description");
                    OnDescriptionChanged();
                }
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDS.DataLayer", Name="PDSRoleTaskMapping")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PDSRoleTaskMapping : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PDSRoleTaskMapping object.
        /// </summary>
        /// <param name="roleID">Initial value of the RoleID property.</param>
        /// <param name="taskID">Initial value of the TaskID property.</param>
        public static PDSRoleTaskMapping CreatePDSRoleTaskMapping(global::System.Int32 roleID, global::System.Int32 taskID)
        {
            PDSRoleTaskMapping pDSRoleTaskMapping = new PDSRoleTaskMapping();
            pDSRoleTaskMapping.RoleID = roleID;
            pDSRoleTaskMapping.TaskID = taskID;
            return pDSRoleTaskMapping;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                if (_RoleID != value)
                {
                    OnRoleIDChanging(value);
                    ReportPropertyChanging("RoleID");
                    _RoleID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("RoleID");
                    OnRoleIDChanged();
                }
            }
        }
        private global::System.Int32 _RoleID;
        partial void OnRoleIDChanging(global::System.Int32 value);
        partial void OnRoleIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TaskID
        {
            get
            {
                return _TaskID;
            }
            set
            {
                if (_TaskID != value)
                {
                    OnTaskIDChanging(value);
                    ReportPropertyChanging("TaskID");
                    _TaskID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TaskID");
                    OnTaskIDChanged();
                }
            }
        }
        private global::System.Int32 _TaskID;
        partial void OnTaskIDChanging(global::System.Int32 value);
        partial void OnTaskIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDS.DataLayer", Name="PDSRx")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PDSRx : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PDSRx object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="patientID">Initial value of the PatientID property.</param>
        /// <param name="productID">Initial value of the ProductID property.</param>
        /// <param name="prescriberID">Initial value of the PrescriberID property.</param>
        /// <param name="refillsAllowed">Initial value of the RefillsAllowed property.</param>
        public static PDSRx CreatePDSRx(global::System.Int32 id, global::System.Int32 patientID, global::System.Int32 productID, global::System.Int32 prescriberID, global::System.Int32 refillsAllowed)
        {
            PDSRx pDSRx = new PDSRx();
            pDSRx.ID = id;
            pDSRx.PatientID = patientID;
            pDSRx.ProductID = productID;
            pDSRx.PrescriberID = prescriberID;
            pDSRx.RefillsAllowed = refillsAllowed;
            return pDSRx;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> WrittenDate
        {
            get
            {
                return _WrittenDate;
            }
            set
            {
                OnWrittenDateChanging(value);
                ReportPropertyChanging("WrittenDate");
                _WrittenDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WrittenDate");
                OnWrittenDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _WrittenDate;
        partial void OnWrittenDateChanging(Nullable<global::System.DateTime> value);
        partial void OnWrittenDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SIG
        {
            get
            {
                return _SIG;
            }
            set
            {
                OnSIGChanging(value);
                ReportPropertyChanging("SIG");
                _SIG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SIG");
                OnSIGChanged();
            }
        }
        private global::System.String _SIG;
        partial void OnSIGChanging(global::System.String value);
        partial void OnSIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ExpirationDate
        {
            get
            {
                return _ExpirationDate;
            }
            set
            {
                OnExpirationDateChanging(value);
                ReportPropertyChanging("ExpirationDate");
                _ExpirationDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExpirationDate");
                OnExpirationDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ExpirationDate;
        partial void OnExpirationDateChanging(Nullable<global::System.DateTime> value);
        partial void OnExpirationDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PatientID
        {
            get
            {
                return _PatientID;
            }
            set
            {
                OnPatientIDChanging(value);
                ReportPropertyChanging("PatientID");
                _PatientID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PatientID");
                OnPatientIDChanged();
            }
        }
        private global::System.Int32 _PatientID;
        partial void OnPatientIDChanging(global::System.Int32 value);
        partial void OnPatientIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ProductID
        {
            get
            {
                return _ProductID;
            }
            set
            {
                OnProductIDChanging(value);
                ReportPropertyChanging("ProductID");
                _ProductID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductID");
                OnProductIDChanged();
            }
        }
        private global::System.Int32 _ProductID;
        partial void OnProductIDChanging(global::System.Int32 value);
        partial void OnProductIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 PrescriberID
        {
            get
            {
                return _PrescriberID;
            }
            set
            {
                OnPrescriberIDChanging(value);
                ReportPropertyChanging("PrescriberID");
                _PrescriberID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PrescriberID");
                OnPrescriberIDChanged();
            }
        }
        private global::System.Int32 _PrescriberID;
        partial void OnPrescriberIDChanging(global::System.Int32 value);
        partial void OnPrescriberIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 RefillsAllowed
        {
            get
            {
                return _RefillsAllowed;
            }
            set
            {
                OnRefillsAllowedChanging(value);
                ReportPropertyChanging("RefillsAllowed");
                _RefillsAllowed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RefillsAllowed");
                OnRefillsAllowedChanged();
            }
        }
        private global::System.Int32 _RefillsAllowed;
        partial void OnRefillsAllowedChanging(global::System.Int32 value);
        partial void OnRefillsAllowedChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDS.DataLayer", Name="PDSTask")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PDSTask : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PDSTask object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="taskName">Initial value of the TaskName property.</param>
        public static PDSTask CreatePDSTask(global::System.String id, global::System.String taskName)
        {
            PDSTask pDSTask = new PDSTask();
            pDSTask.ID = id;
            pDSTask.TaskName = taskName;
            return pDSTask;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.String _ID;
        partial void OnIDChanging(global::System.String value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TaskName
        {
            get
            {
                return _TaskName;
            }
            set
            {
                if (_TaskName != value)
                {
                    OnTaskNameChanging(value);
                    ReportPropertyChanging("TaskName");
                    _TaskName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("TaskName");
                    OnTaskNameChanged();
                }
            }
        }
        private global::System.String _TaskName;
        partial void OnTaskNameChanging(global::System.String value);
        partial void OnTaskNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Description
        {
            get
            {
                return _Description;
            }
            set
            {
                OnDescriptionChanging(value);
                ReportPropertyChanging("Description");
                _Description = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Description");
                OnDescriptionChanged();
            }
        }
        private global::System.String _Description;
        partial void OnDescriptionChanging(global::System.String value);
        partial void OnDescriptionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PDS.DataLayer", Name="PDSUser")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class PDSUser : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new PDSUser object.
        /// </summary>
        /// <param name="id">Initial value of the ID property.</param>
        /// <param name="firstName">Initial value of the FirstName property.</param>
        /// <param name="lastName">Initial value of the LastName property.</param>
        /// <param name="userID">Initial value of the UserID property.</param>
        /// <param name="password">Initial value of the Password property.</param>
        public static PDSUser CreatePDSUser(global::System.Int32 id, global::System.String firstName, global::System.String lastName, global::System.String userID, global::System.String password)
        {
            PDSUser pDSUser = new PDSUser();
            pDSUser.ID = id;
            pDSUser.FirstName = firstName;
            pDSUser.LastName = lastName;
            pDSUser.UserID = userID;
            pDSUser.Password = password;
            return pDSUser;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String UserID
        {
            get
            {
                return _UserID;
            }
            set
            {
                OnUserIDChanging(value);
                ReportPropertyChanging("UserID");
                _UserID = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("UserID");
                OnUserIDChanged();
            }
        }
        private global::System.String _UserID;
        partial void OnUserIDChanging(global::System.String value);
        partial void OnUserIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> RoleID
        {
            get
            {
                return _RoleID;
            }
            set
            {
                OnRoleIDChanging(value);
                ReportPropertyChanging("RoleID");
                _RoleID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("RoleID");
                OnRoleIDChanged();
            }
        }
        private Nullable<global::System.Int32> _RoleID;
        partial void OnRoleIDChanging(Nullable<global::System.Int32> value);
        partial void OnRoleIDChanged();

        #endregion

    
    }

    #endregion

    
}
